### ISSUE TITLE
Improve the LDAP integration

### ISSUE THREAD

**Issue by jeromelebleu** [YunoHost-Apps/wallabag2_ynh#1]
The LDAP is currently only integrated for the user authentication - using the HTTP basic auth credentials provided by the SSO - who must be already created in the Wallabag database. This is done by this [patch](https://github.com/YunoHost-Apps/wallabag2_ynh/blob/master/patches/00-ldap-auth.patch) thanks to the [Symfony LDAP Component](http://symfony.com/blog/new-in-symfony-2-8-ldap-component) - suggested [here](https://github.com/wallabag/wallabag/issues/966) by @nicosomb - and users are created [here](https://github.com/YunoHost-Apps/wallabag2_ynh/blob/master/scripts/install#L74-L75) at the install.

It "works", but I really don't know a lot about Symfony and I'm sure it can be improved - waiting that it's fully integrated into Wallabag, see https://github.com/wallabag/wallabag/issues/966 for that. Also, if it's possible to manage the user creation directly from Wallabag...

So, any help, review, advices or - even better - pull-request is really welcome! :) Thanks in advance!

**Comment by malmsey** [comment]
Hello, and thanks for working on this package.

To what extent does it actually "work" right now?  Is there a default account that I can sign into or do I have to wait for user management to be functional before I use wallabag?  If I knew what I was doing I could answer this question myself or even contribute, but I have very little idea what I'm doing :).

**Comment by lapineige** [comment]
For your information I've a test server available, if you need some tests from an user point-of-view, please ping me ;)

**Comment by jeromelebleu** [comment]
@malmsey, @lapineige Thanks for your contribution offer! :) I'll let you know as soon as it needs tests, but currently I'm still waiting for reviews & feedbacks from Wallabag developers...

@malmsey The installation "works" and each YunoHost user is created in Wallabag.

**Comment by tcitworld** [comment]
Hi,

@jeromelebleu Thanks a lot for your patch. We'll see to integrate it and make ldap user management as a setting as soon as possible (TM).

**Comment by jeromelebleu** [comment]
@tcitworld Thanks! Note anyway that I don't know a lot Symfony and that I didn't try with v3.1... But according to the [official documentation](http://symfony.com/doc/current/cookbook/security/ldap.html), it seems that it didn't changed. I'll wait that you integrate it in Wallabag directly before publishing this app, what do you think?

**Comment by jeromelebleu** [comment]
@tcitworld Also, do you think there is a way to create Wallabag users "on the fly" when using LDAP authentication please?
In other words, when a new user is added in YunoHost - and so in LDAP, is it possible to create its relevant Wallabag user when he/she authenticate to Wallabag - instead of manually creating it with YunoHost hooks, as at the [installation](https://github.com/YunoHost-Apps/wallabag2_ynh/blob/master/scripts/install#L69-L76)?

**Comment by tcitworld** [comment]
If I understand things correctly that may require something like FR3DLdapBundle.

**Comment by malmsey** [comment]
Oh, I only now understand that not having LDAP authentication means the android app won't work.  And I thought it was all a certificate problem on my end.  
Any news on this front?

**Comment by lapineige** [comment]
> Oh, I only now understand that not having LDAP authentication means the android app won't work. And I thought it was all a certificate problem on my end.

Any app using the API won't work isn't it ?
Except from the browser ? A webapp could do it ?
(yes I thinking to this: https://github.com/wallabag/wallabag-fxos - adapting it to be a pure webapp will allow android/ios/WP users to use it too)

**Comment by jeromelebleu** [comment]
> Any app using the API won't work isn't it ?

No, the LDAP integration is done with this app - contrary to the v1 package. It should work using the API. Please let me know if it's not the case.

**Comment by malmsey** [comment]
> It should work using the API. Please let me know if it's not the case.
I could not get the android app to work.  Have you had a chance to test it?

**Comment by raf64flo** [comment]
Hi, I've just installed Wallabag 2.0.5 using your repository, it works like a charm even in Android app using the same parameters as for v1.9.2 (expect the token which I've regenerated).
Thanks a lot!

**Comment by jeromelebleu** [comment]
Great! Thanks for your tests & feedbacks!

**Comment by zero1Dre** [comment]
Hi, I've just installed YunoHost and Wallabag 2 using your repository. Great job, thanks!

I have one issue however, which seems related to this thread (sorry if it isn't): the iOS app is not able to connect to my wallabag (user/pass not working). I have also created a client (client ID/pass). Is this related to the authentication API?

Does anyone have an idea as to why this isn't working (yet)? 

Thanks

**Comment by tcitworld** [comment]
Isn't there a « http credentials » section in the iOS app ? It should correspond to your YunoHost credentials.

**Comment by zero1Dre** [comment]
@tcitworld there is a client_id and client_secret section and also a username/password.
For the client_id/secret, I have created a client via the web interface and have copy-pasted the values in the iOS app (I have not generated a token via http POST however).
Thanks

**Comment by zero1Dre** [comment]
OK, so I may have found a dirty workaround. When creating the user in the wallabag database at [installation](https://github.com/YunoHost-Apps/wallabag2_ynh/blob/master/scripts/install#L72), a random password is generated, which is then used by the iOS (and maybe Android) Wallabag app.

To work around this, I reset my wallabag password using the wallabag link (after having logged out of YunoHost SSO) then set the password to the username of my YunoHost instance.

Hope this helps.

**Comment by JimboJoe** [comment]
From my understanding, the LDAP integration only works from the web interface, and doesn't work with oauth. It means it won't work with "modern" (Android, iOS, etc.) clients.
@zero1Dre workaround indeed works, but that is not satisfying as such.
@tcitworld Do you confirm the diagnostic and do you see any chance to implement complete LDAP integration on Wallabag side or make a better patch on the YunoHost app side?

**Comment by JimboJoe** [comment]
The situation is OK now: OAuth login has been fixed [here](https://github.com/YunoHost-Apps/wallabag2_ynh/pull/28).
I propose to close this issue for now, as it's very frightening as opposed to the current package situation (working 100%).
