### ISSUE TITLE
Update to 2.1

### ISSUE THREAD

**Issue by lapineige** [YunoHost-Apps/wallabag2_ynh#10]
Wallabag 2.1 is out :) https://www.wallabag.org/blog/2016/10/04/wallabag-211

Could you update this app to the 2.1 ? Thanks ! :)
(in case you need any test, just ping me)

**Comment by jeromelebleu** [comment]
Done with https://github.com/YunoHost-Apps/wallabag2_ynh/commit/7d181edb0f855db45c0e1aded65b09d60f410027!

@lapineige feel free to try it and report any issues, thanks in advance! If you can also try the import using Redis - which needs to be enabled in the *Internal Settings* first yet, it would be wonderful! :) If it's working fine, I'll see to enable it by default.

**Comment by lapineige** [comment]
Thanks a lot ! 
Testing it right now :)

> If you can also try the import using Redis

What is Redis ?

**Comment by lapineige** [comment]
First test done: after 1h at <1% CPU usage, no article fetched  :(

**Comment by jeromelebleu** [comment]
Sorry, I didn't read the documentation entirely, there is something more to do: see [here](http://doc.wallabag.org/en/master/developer/redis.html#launch-redis-consumer). As it's not trivial and regarding your tests, I'm wondering if keeping the normal import should be enough... What do you think about that?

**Comment by lapineige** [comment]
Ok, I will try I as soon as I will be able to purge my article list (I had some advices here: https://github.com/wallabag/wallabag/issues/1981#issuecomment-252510503) as I don't want to un-install and install again (with a new config, ...) for every test ^^

**Comment by lapineige** [comment]
Ok, I found how to do this. (solution here: https://github.com/YunoHost-Apps/freshrss_ynh/issues/15)

> Sorry, I didn't read the documentation entirely, there is something more to do: see here.

I'm not sure to understand what I should do. Running the command just raise a command not found error.

**Comment by lapineige** [comment]
It seems like I'm not the only one having this issue: https://forum.yunohost.org/t/wallabag-import-de-la-v1-vers-v2/2061

Should we open a ticket on wallabag repo, or do you think it's something specific to Yunohost ?

**Comment by nicosomb** [comment]
Tell us if we need to do something on @wallabag.

**Comment by lapineige** [comment]
That's the question, but I don't know if it's something related to wallabag or specific to this package.

**Comment by lapineige** [comment]
For info, the 2.1.3 version is out :)
https://www.wallabag.org/blog/2016/11/04/wallabag-213

-----

I've more information about redis import. (https://forum.yunohost.org/t/wallabag-import-de-la-v1-vers-v2/2061/9)
It's more interesting for a Pocket (for instance) import, as wallabag export content, while Pocket export url only.
So the impact on server is much bigger for a Pocket import. Redis is a good choice in that case.
