### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by buzuck** [YunoHost-Apps/wallabag2_ynh#11]
Hello,

I have an unkown error occuring at [line 66](https://github.com/YunoHost-Apps/wallabag2_ynh/blob/master/scripts/install#L66) during the installation. All seems to go well, but it swaps to the remove script after attempting to create the database.
 
Here is what I get using in CLI, using the `--verbose` option. The  `--debug` is pretty much the same, the severity is always `INFO` on those lines.

`+ sudo chown -R www-data: /var/www/wallabag2`
`+ exec_console www-data /var/www/wallabag2 wallabag:install`
`+ local AS_USER=www-data`
`+ local WORKDIR=/var/www/wallabag2`
`+ shift 2`
`+ cd /var/www/wallabag2`
`+ exec_as www-data php bin/console --no-interaction --env=prod wallabag:install`
`+ local USER=www-data`
`+ shift 1`
`++ whoami`
`+ [[ www-data = admin ]]`
`+ sudo sudo -u www-data php bin/console --no-interaction --env=prod wallabag:install`
`Installing Wallabag...`
`Step 1 of 4. Checking system requirements.`
`+---------------------+--------+----------------+`
`| Checked             | Status | Recommendation |`
`+---------------------+--------+----------------+`
`| PDO Driver          | OK!    |                |`
`| Database connection | OK!    |                |`
`| curl_exec           | OK!    |                |`
`| curl_multi_init     | OK!    |                |`
`+---------------------+--------+----------------+`
`Success! Your system can run Wallabag properly.`
`Step 2 of 4. Setting up database.`
`Creating schema`
`Clearing the cache`
`Executing script '/var/cache/yunohost/from_file/wallabag2_ynh-master/scripts/remove'...`
` [ the rest of the remove script ] `

**Comment by jeromelebleu** [comment]
Hi @buzuck, it'll be really hard to find what's the issue with your log... :/ Can you five more details about your hardware at least please? Also, did you tried to try again the installation? Is it still failing at the same line?

**Comment by buzuck** [comment]
Well... nevermind. I just tried to reproduce and get a little more logs, and it just installed flawlessly.

C'est tombé en marche. Magie !

**Comment by jeromelebleu** [comment]
Well well well! :)
