### ISSUE TITLE
official 2.3.8 migration to 2.4.2 in YNH 

### ISSUE THREAD

**Issue by xmgz** [YunoHost-Apps/wallabag2_ynh#113]
Hi,

I'm using YNH 4.2.8.3 (stable) in a raspi4 

We can read in the wallabag_ynh2 README that:

`Shipped version: 2.4.2~ynh2`

but installing from webadmin (or command line "wallabag2") installs version 2.3.8 and no update available to version 2.4.x

Please, would you tell me (us) how to upgrade to official 2.4.2 version you provide here? thanks

I've tried to install "testing" branch version but got an error (this is another issue though, I will post log).

**Comment by lapineige** [comment]
Indeed official version is still 2.3.8.
We might have made a mistake when reverting (kind of cancelling) the upgrade to 2.4.2 (https://github.com/YunoHost-Apps/wallabag2_ynh/pull/101#issuecomment-855456648) - ping @alexAubin, any clue ?

You can try 2.4.2 using this PR : https://github.com/YunoHost-Apps/wallabag2_ynh/pull/106 (branch : https://github.com/YunoHost-Apps/wallabag2_ynh/tree/revert-105-revert-101-testing).

Any log if it fails would be highly appreciated. Please be aware that might not be 100% safe.

**Comment by mikeorlov** [comment]
On August 2 I've successfully updated from 2.3.8 to 2.4.2 using branch : https://github.com/YunoHost-Apps/wallabag2_ynh/tree/revert-105-revert-101-testing
But today, when I've tried to do the same upgrade from 2.3.8 to 2.4.2 (testing the #106), the upgrade failed with an error: "WARNING ERROR 1146 (42S02) at line 1: Table 'wallabag2.craue_config_setting' doesn't exist".
Here is the full log: https://paste.yunohost.org/raw/ucequrosuy

**Comment by mikeorlov** [comment]
It seems that I messed with command for update and used "testing" branch instead of "revert-105-revert-101-testing" branch.
Clean installation, as well as update from 2.3.8, using "revert-105-revert-101-testing" branch works fine.

**Comment by lapineige** [comment]
We remove that PR #106 to try again an upgrade to 2.4.2 (not ready yet).
