### ISSUE TITLE
upgrade from 2.3.8 to testing branch failed

### ISSUE THREAD

**Issue by xmgz** [YunoHost-Apps/wallabag2_ynh#114]
raspi4 at home
latest YNH 4.2.8.3 stable
no manual modifications

trying to ugrade to testing branch failed

full log: https://paste.yunohost.org/raw/yikayaciqa

this could be relevant

```
Warning: ERROR 1146 (42S02) at line 1: Table 'wallabag2.craue_config_setting' doesn't exist
Warning: [Error] Upgrade failed.
Warning: The app was restored to the way it was before the failed upgrade.
```

thank you for your work

**Comment by lapineige** [comment]
#106
