### ISSUE TITLE
Update to 2.1.4

### ISSUE THREAD

**Issue by lapineige** [YunoHost-Apps/wallabag2_ynh#13]
[Wallabag 2.1.4](https://www.wallabag.org/blog/2016/11/19/wallabag-214) is out :)

As always, I'd be happy to test it if needed :)

**Comment by jeromelebleu** [comment]
Done with https://github.com/YunoHost-Apps/wallabag2_ynh/commit/16340deabeac6cd5809320d1ab54d32af17d0312! Feel free to test it, thanks!

**Comment by lapineige** [comment]
Great, super fast update ! 

Using it right now, nothing to report :)

**Comment by lapineige** [comment]
Oh by the way there is already a new update, 2.1.5: https://www.wallabag.org/blog/2016/11/21/wallabag-215
With just a php version change.
As always, no hurry, take your time for the update ;)

**Comment by jeromelebleu** [comment]
Regarding the really minor change, I'll wait the next version to update the package since it'is moreover not impacted by that. Thanks for the report ant your tests by the way with the last update!

**Comment by lapineige** [comment]
That's sound reasonable :)

Actually I encountered a small "issue": there's a drop-down message saying something like Annotation storage failed, Internal error 500.
But by the way annotations work as usual, on old and new articles.
