### ISSUE TITLE
Problem with bookmarklet and FF add-on

### ISSUE THREAD

**Issue by Thomas830** [YunoHost-Apps/wallabag2_ynh#14]
Hello,
Since last update I have a few blocking problems.
For the Firefox extension I think it's because of SSO because it keeps rejecting me if I try to connect to my YNH instance.
The other problem is more blocking for me: I have an error 500 when using the bookmarklet. I found that in my logs:

`2016/11/29 21:58:18 [error] 4177#0: *1082558 rewrite or internal redirection cycle while redirect to named location "@wallbag2", client: 92.171.104.151, server: domaine.tld, request: "GET /wallabag/bookmarklet?url=https://linuxfr.org/users/rodhlann/journaux/des-basheries HTTP/1.1", host: "domaine.tld", referrer: "https://linuxfr.org/users/rodhlann/journaux/des-basheries"`

I also have an error 500 when trying to export to PDF

I'm available if you need more informations or tests just ping me ! :-)

**Comment by lapineige** [comment]
I've those issues too.

> For the Firefox extension I think it's because of SSO because it keeps rejecting me if I try to connect to my YNH instance.

It wasn't working for me before, so I don't think it's related to this update.

> I also have an error 500 when trying to export to PDF

And other formats.

Sorry @jeromelebleu , sounds like I should make a complete test of the app before telling you the update is working fine. I'll keep that in mind for future tests :)

**Comment by Thomas830** [comment]
A little update: issue with bookmarklet is solved by modifying /etc/nginx/domain.tld.d/wallabag2.conf
replacing in `location @wallbag2`
`rewrite ^ /wallabag/app.php$is_args$args;`
with:
`rewrite ^ /wallabag/app.php?is_args$args;`

**Comment by lapineige** [comment]
Thanks a lot, it's working on my side :)

I think you can make a PR to solve this issue for other users ;)

**Comment by Thomas830** [comment]
Done!

**Comment by lapineige** [comment]
Cool, thanks ! :)
@jeromelebleu : on my side it's working fine, and no new bug to report.

**Comment by lapineige** [comment]
(Reacting to the PR comments):
That's pretty strange indeed that breaking the request line solves the issue of sharing with the bookmarklet.
I guess we should take a lot to nginx conf/log to know what's blocked by this, to know what was blocking the bookmarklet.
I'm going to break (or to fix, in some way ^^) my configuration again, and watch the logs for errors during this operation.
