### ISSUE TITLE
Cannot update to 2.4.3: An exception occurred while executing 'ALTER TABLE entry ADD given_url LONGTEXT DEFAULT NULL, ADD hashed_given_url TINYTEXT DEFAULT NULL'

### ISSUE THREAD

**Issue by mdic** [YunoHost-Apps/wallabag2_ynh#143]
### Describe the bug

Wallabag cannot be updated due to the following error

`Error thrown while running command "--no-interaction --env=prod doctrine:migrations:migrate". Message: "An exception occurred while executing 'ALTER TABLE entry ADD given_url LONGTEXT DEFAULT NULL, ADD hashed_given_url TINYTEXT DEFAULT NULL'`

### Context

- Hardware: *VPS bought online*
- YunoHost version: 4.3.6.3
- I have access to my server: *Through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

### Steps to reproduce

Try to update Wallabag from `2.3.8~ynh4` to `2.4.3~ynh1` from the webadmin "System update" tool

### Expected behavior

The app should update

### Logs

https://paste.yunohost.org/raw/tokaconera

**Comment by lapineige** [comment]
Could you give a try to this PR please ?
`yunohost app upgrade wallabag2 -u https://github.com/YunoHost-Apps/wallabag2_ynh/tree/fix_dependencies`

**Comment by El-Gavy** [comment]
@lapineige no access to CLI for the moment, has it been merged to master (so that i could try a "normal" upgrade)

**Comment by lapineige** [comment]
Yes indeed, I forgot to update this :)

**Comment by klorydryk** [comment]
Just tried to update to 2.5.0 : got the same error.

**Comment by mdic** [comment]
I can confirm that upgrading to Wallabag 2.5.0 ynh2 solves the previous issue, and Wallabag is now correctly upgrading.

**Comment by lapineige** [comment]
So now how to find why some errors are resolved and not others.

**Comment by Salamandar** [comment]
Should be fixed
