### ISSUE TITLE
missing feature : Save by email

### ISSUE THREAD

**Issue by gtrdblt** [YunoHost-Apps/wallabag2_ynh#156]
Hello, 

I've just seen that there's a feature that is missing compared to the "standalone" application, which is "save by email", that allows you to create an entry by sending an url by mail. 

This feature seems to be available since april 2020 (see https://www.wallabag.it/en/news/week-17-whats-new-on-wallabag-it and https://github.com/wallabag/wallabag/issues/239), so since version 2.4.0 of the original app.

Would it be possible to enable it on yunohost ? It would be quite awesome.

Thanks !

**Comment by lapineige** [comment]
Did you enable it in the config settings ?

I can use that feature, so I'm surprised it doesn't work on your side, we did not configure anything to disable this feature :thinking:

**Comment by gtrdblt** [comment]
Unfortunately, I don't have the tab for the option on my configuration interface, even on a fresh installation of wallabag (I tried yesterday).

**Comment by lapineige** [comment]
It should be in *Internal configuration -> Article*. Can you config you don't have this tab/particular setting ?
If so, then it's probably a bug…

**Comment by lapineige** [comment]
Oh now I understand !
I didn't know there was such a feature ! :-o

Then I have no idea how it is supposed to work… And I don't have time to investigate it (read the doc, ask developers…) right now, sorry.

**Comment by gtrdblt** [comment]
No worries, don't worry! 

I'll take a look, I didn't see anything here that would cause a problem in the installation scripts, it's probably a configuration issue. 

I wonder if wallabag would do a check on a local mail config to be able to retrieve them automatically (like a local postfix or something like that), and that there simply yunohost doesn't answer him correctly. So, it would disable the functionality.

**Comment by gtrdblt** [comment]
OK, it's a special feature : 

https://github.com/wallabag/wallabag/issues/6561#issuecomment-1567449771

Closing ticket.

**Comment by gtrdblt** [comment]
OK, it's a special feature :

https://github.com/wallabag/wallabag/issues/6561#issuecomment-1567449771

Closing ticket.
