### ISSUE TITLE
Cannot use the API (bad username/password combination)

### ISSUE THREAD

**Issue by roukydesbois** [YunoHost-Apps/wallabag2_ynh#16]
Hello!

Thanks for the app :)

I'm trying to set up the iOS app, and the ttrss to wallabag v2 plugin with my wallabag v2 which I host on my Yunohost, and it doesn't work.

I tried via curl and I get the {"error":"invalid_grant","error_description":"Invalid username and password combination"} error message when I use my ynh username and password.
I have created a user in the wallabag users management interface and I managed to use the API via curl, so it looks like the YNH username and/or password is not properly recognized by the wallabag API.

I have looked for a cause in the ynh package but I'm still new, would you have any idea why this happens?

Thanks!

**Comment by IImtt** [comment]
Same problem here. Can't use the API; so Android app isn't working.

Regards.

**Comment by zero1Dre** [comment]
Hi, I may have found a dirty workaround for this, which I've shared in issue #1 
Hope this works for you.

**Comment by roukydesbois** [comment]
Thanks @zero1Dre it worked like a charm for me! I'll let the issue open, and will find time to have a look at it.

**Comment by JimboJoe** [comment]
@roukydesbois @zero1Dre The latest commit should fix the problem. Could you please try changing your YunoHost password and connecting to you Wallabag account?

**Comment by zero1Dre** [comment]
@JimboJoe @roukydesbois Works for me! Great job! Thank you ;)

**Comment by roukydesbois** [comment]
@JimboJoe @zero1Dre it worked for me too! At install, and change of password. Thanks a lot!
