### ISSUE TITLE
Problèmes bookmarklet et config

### ISSUE THREAD

**Issue by tomgue** [YunoHost-Apps/wallabag2_ynh#18]
Hello,
J'ai quelques problèmes avec mon instance de wallabag V2
* Le bookmarklet (/wallabag/bookmarklet?url=http...) me renvoi un 500 Internal Server Error nginx
* Quand je change la langue dans la version web elle n'est pas sauvegarder, en anglais par defaut

et l'appli android ne veux pas sauvegarder un article (pas de prob avec la version web) mais bon ça c'est autre chose...

**Comment by jeromelebleu** [comment]
Salut @tomgue,

Pour ton premier problème, c'est déjà reporté ici #14, aucune origine du problème n'a encore été trouvée.

Pour le problème de langue, c'est déjà connu, regarde #2 et plus particulièrement https://github.com/YunoHost-Apps/wallabag2_ynh/issues/2#issuecomment-233755771.

Je ferme donc ton ticket, vu que cela en duplique d'autres. N'hésite pas à régir sur ceux-là à la place.
