### ISSUE TITLE
Wallabag 2.2 is out

### ISSUE THREAD

**Issue by lapineige** [YunoHost-Apps/wallabag2_ynh#19]
Wallabag 2.2 was just released. Here are the notes: https://wallabag.org/en/news/new-release-wallabag-2-2-finally

@jeromelebleu If you need help when testing the update, don't hesitate to ask me :)

**Comment by jeromelebleu** [comment]
@lapineige Thanks for the note!

However, I don't use this application anymore and I choose to pursue other horizons. That's why I'm looking for someone else to maintain this package. Do not hesitate if you're interested in, I can support you if you need!

**Comment by lapineige** [comment]
> However, I don't use this application anymore and I choose to pursue other horizons. 

Well, thanks for all the work made so far :smiley:

> That's why I'm looking for someone else to maintain this package. Do not hesitate if you're interested in, I can support you if you need!

I'm very new to Yunohost packaging (trying to update shaarli now) and have really little time, but I would be happy to help :)  (if any interested person read this, it would be easier if we are several ;)
From what I saw so far, it doesn't seem to be a huge task for most of the update, just updating some sha256sum stuff :)
Your help would be really welcome to tell me what's important to keep in mind when updating, the changes/choices you made, and so on.

**Comment by jeromelebleu** [comment]
> Well, thanks for all the work made so far :smiley:

You're welcome, thanks for your tests and so!

> I'm very new to Yunohost packaging (trying to update shaarli now) and have really little time, but I would be happy to help :) (if any interested person read this, it would be easier if we are several ;)

It could be a good idea in that case to do it with at least another person, I agree! But as you said, it's not a big work... Even if the packaging could be improved, e.g. add backup & restore scripts.

> Your help would be really welcome to tell me what's important to keep in mind when updating, the changes/choices you made, and so on.

I added a [small shell script](https://github.com/YunoHost-Apps/wallabag2_ynh/blob/master/update.sh) that I used to update the Wallbag version. Feel free to try it, improve it, ... This script is generally enough for minor release, but not always for major ones... In that case, here are some ideas regarding what this package changes in Wallbag:

 - check the upstream `parameter.yml` changes [here](https://github.com/wallabag/wallabag/blob/2.2.0/app/config/parameters.yml.dist) in case some variables are missing from [here](https://github.com/YunoHost-Apps/wallabag2_ynh/blob/master/conf/parameters.yml)
 - check if [patches](https://github.com/YunoHost-Apps/wallabag2_ynh/tree/master/patches) are well applied - waiting an upstream or better integration - by trying to install and upgrade the application

Hope that it will help! Anyway, feel free to ask me - or YunoHost contributors or also on the forum - for any further help.

**Comment by lapineige** [comment]
> Even if the packaging could be improved, e.g. add backup & restore scripts.

Wallabag already has a backup tool - even if it's far from complete for Yunohost usage, it's correct.
So as I don't have many time I won't tackle this point soon.

> I added a small shell script that I used to update the Wallbag version. Feel free to try it, improve it, ... This script is generally enough for minor release, but not always for major ones... In that case, here are some ideas regarding what this package changes in Wallbag:
>   * check the upstream parameter.yml changes here in case some variables are missing from here
>  *  check if patches are well applied - waiting an upstream or better integration - by trying to install and upgrade the application

Thanks, I'll take a look at those things :)

> Anyway, feel free to ask me - or YunoHost contributors or also on the forum - for any further help.

Indeed I'll probably post on the forum to ask for help and feedback :)

Thanks for your help ! :)

**Comment by lapineige** [comment]
> also, could you give me access to repo edition ? It might help for further work ^^

Ping @jeromelebleu  :)

**Comment by jeromelebleu** [comment]
@lapineige sorry, I wasn't be notified by your post update where you ask for the access...

**Comment by lapineige** [comment]
That's what I thought, no problem :)

**Comment by lapineige** [comment]
It seems that the update will be more complex: http://doc.wallabag.org/en/master/user/upgrade.html#upgrading-from-2-1-x-to-2-2-x
2 methods, depending of the version.
@jeromelebleu, what do you think I should do here ? Update to 2.2.0 and then another update to the next one ?
(and how to handle that if the same thing happen in the future ?)

For now I'll try to make the installation working, and next the update.

**Comment by lapineige** [comment]
@nicosomb can I ask you some help here ?

I'm trying to port the package to 2.2.1 (from 2.1.4). I encounter issues that I had on 2.1.4 installation too.

It sound like I have multiple errors:
* First I added to this file https://github.com/YunoHost-Apps/wallabag2_ynh/blob/master/conf/parameters.yml one missing parameter (database_charset) https://github.com/YunoHost-Apps/wallabag2_ynh/pull/20/commits/bd71f60af80a36f7f00282afc043320867cab96e
* Then a second one (rabbitmq_prefetch_count) https://github.com/YunoHost-Apps/wallabag2_ynh/pull/20/commits/3f8a193c31f6ec831e6f11fe39f47471b8f5c4a0
* And now during this command:  `sudo sudo -u www-data php /var/www/wallabag2/bin/console --no-interaction --env=prod wallabag:install` (I don't know why there is 2 sudo, but at least it works)
I have another issue that I don't understand:
> Attention : 
Attention : 
Attention :   [Symfony\Component\Config\Exception\FileLoaderLoadException]
Attention :   The file "/var/www/wallabag2/app/config/parameters.yml" does not contain valid YAML in /var/www/wallabag2/app/config/parameters.yml (which is being imported from "/var/www/wallabag2/app/config/config.yml").
Attention : 
Attention : 
Attention : 
Attention :   [Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]
Attention :   The file "/var/www/wallabag2/app/config/parameters.yml" does not contain valid YAML.
Attention : 
Attention : 
Attention : 
Attention :   [Symfony\Component\Yaml\Exception\ParseException]
Attention :   Unable to parse at line 47 (near "b").
Attention : 
Attention : 

Do you know what's going on ? Thanks :)

**Comment by jeromelebleu** [comment]
> It seems that the update will be more complex: http://doc.wallabag.org/en/master/user/upgrade.html#upgrading-from-2-1-x-to-2-2-x

I don't think so, the `upgrade` script should work fine since it's already calling the right and suggested commands, see [here](https://github.com/YunoHost-Apps/wallabag2_ynh/blob/master/scripts/upgrade#L49-L50). The installation made by this package is a mix of the *on a dedicated web server* and *on a shared hosting* methods. It fetch the archive which contains sources and vendor stuff - the *on a shared hosting* method - and call the commands suggested by the *on a dedicated web server* method.

> I have another issue that I don't understand:

Could you paste your `app/config/parameters.yml` file content please? It's wired since there is no line 47...

**Comment by lapineige** [comment]
>  I don't think so, the upgrade script should work fine since it's already calling the right and suggested commands, see here. The installation made by this package is a mix of the on a dedicated web server and on a shared hosting methods. It fetch the archive which contains sources and vendor stuff - the on a shared hosting method - and call the commands suggested by the on a dedicated web server method.

Sounds like you did a pretty good job ! :)
So live will be easier for me. Thanks :D

> Could you paste your app/config/parameters.yml file content please? It's wired since there is no line 47...

Uh... stupid mistake, didn't spot that "b" ^^
I fixed that.
I'm currently testing on this branch: https://github.com/lapineige/wallabag2_ynh/blob/lapineige-patch-1/conf/parameters.yml

**Comment by lapineige** [comment]
I made some changes to line 48 (original https://github.com/YunoHost-Apps/wallabag2_ynh/blob/master/scripts/_common.sh#L48) to know where is the issue: https://github.com/lapineige/wallabag2_ynh/blob/lapineige-patch-1/scripts/_common.sh#L48.

So now the line execute `(exec_as "$AS_USER" php "/var/www/wallabag2/bin/console" --no-interaction --env=prod $@)`
And raise this `Permission denied` issue. I dodn't understand why, as the file owner was changed before.

**Comment by jeromelebleu** [comment]
Before going any further, I really advise you - if possible - to work in a development environment to test the package and your changes instead of doing a lot of small commits and - I guess - use this repository to try... It sounds maybe a lot of work but will help and ease you after that! Also, the commits history will be cleaner! :)

**Comment by lapineige** [comment]
> Before going any further, I really advise you - if possible - to work in a development environment to test the package and your changes instead of doing a lot of small commits and - I guess - use this repository to try...

I'm testing on a VM, and all those test commits are made on my fork (and under a sub-branch that will be deleted once done).

> Also, the commits history will be cleaner! :)

That's my main reason ^^

**Comment by lapineige** [comment]
> Before going any further, I really advise you - if possible - to work in a development environment to test the package and your changes instead of doing a lot of small commits and - I guess - use this repository to try...

I'm testing on a VM, and all those test commits are made on my fork (and under a sub-branch that will be deleted once done).

> Also, the commits history will be cleaner! :)

That's my main reason ^^

**Comment by lapineige** [comment]
Ok so after some more changes and parameter addition, install works (Yunohost 2.5).

But then I have an `Internal error in annotation store! (Error 500)` on the article view, and all articles are empty.
On the main page, a GET request fails, searching for this file: `/var/www/wallabag2/web/js/routing.js`. But the folder contains only `fos_js_routes.js`.
I don't know if that's the issue.

**Comment by lapineige** [comment]
Reading the logs, the exact issues are:
* when adding an entry:
`app.ERROR: Error while saving an entry {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 2 passed to Wallabag\\CoreBundle\\GuzzleSiteAuthenticator\\GrabySiteConfigBuilder::__construct() must be of the type array, null given, called in /var/www/wallabag2/var/cache/prod/appProdProjectContainer.php on line 6340 and defined at /var/www/wallabag2/src/Wallabag/CoreBundle/GuzzleSiteAuthenticator/GrabySiteConfigBuilder.php:27)","entry":"[object] (Wallabag\\CoreBundle\\Entity\\Entry: {})"} []`

* when accessing to it:
`request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /bundles/fosjsrouting/js/router.js" (from "https://pleasedeleteme.noho.st/wallabag/")" at /var/www/wallabag2/var/cache/prod/classes.php line 3915 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /bundles/fosjsrouting/js/router.js\" (from \"https://pleasedeleteme.noho.st/wallabag/\") at /var/www/wallabag2/var/cache/prod/classes.php:3915, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/wallabag2/var/cache/prod/appProdProjectContainerUrlMatcher.php:880)"} []`

**Comment by tcitworld** [comment]
Testing this myself.

**Comment by lapineige** [comment]
Ok great :)
I should have more time to investigate within a week.

**Comment by JimboJoe** [comment]
Implemented by PR [#24](https://github.com/YunoHost-Apps/wallabag2_ynh/pull/24)
