### ISSUE TITLE
Upgrading to 2.5.4~ynh3 seems to delete images saved locally

### ISSUE THREAD

**Issue by kr-cr** [YunoHost-Apps/wallabag2_ynh#201]
### Describe the bug

Hi, It seems the upgrade from 2.5.4-ynh2 to 2.5.4-ynh3 removes images saved locally. I tried to restore 2.5.4~ynh2 pre-update backup and apply the upgrade again but images does not show up in the wallabag interface after upgrading. (and are actually not in their folders in '/var/www/wallabag2/web/assets'

I don't know how to check what's changed in this upgrade that could cause this. 

Thank you for any help.

### Context

- Hardware: RPI 3B+
- YunoHost version: 11.2.10.3 (stable)
- I have access to my server: Through the webadmin and SSH
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no, but Wallabag is configured to save image locally. 
- Using, or trying to install package version/branch: 2.5.4~ynh3
- If upgrading, current package version: 2.5.4~ynh2

### Steps to reproduce

1. Go to Web Admin → System update
2. Upgrade to Wallabag 2.5.4~ynh3
3. The upgrade proceeds properly
4. Going back to wallabag, the images does not load anymore and checking in '/var/www/wallabag2/web/assets' there is no images anymore.

### Expected behavior

The images should not be deleted.

**Comment by nicofrand** [comment]
I have the same issue (just noticed now). I was able to retrieve the images from the backup though (in web/assets/images).

**Comment by kr-cr** [comment]
Thanks for the feedback. So did you just just put them back from the backup where they should be? I restored the pre-update backup for now because I didn't know if doing this was a good solution but if that's the case I could try.

**Comment by lapineige** [comment]
I don't understand what could change it in https://github.com/YunoHost-Apps/wallabag2_ynh/blob/master/scripts/upgrade

Do you have the upgrade log ?

**Comment by kr-cr** [comment]
Yes, it should be this one: 

[20240404-191823-app_upgrade-wallabag2.log](https://github.com/YunoHost-Apps/wallabag2_ynh/files/15049081/20240404-191823-app_upgrade-wallabag2.log)

**Comment by nicofrand** [comment]
> Thanks for the feedback. So did you just just put them back from the backup where they should be?

Yes (untar the folder I wanted, in /web/assets/images IIRC)!

**Comment by nicofrand** [comment]
> I don't understand what could change it in https://github.com/YunoHost-Apps/wallabag2_ynh/blob/master/scripts/upgrade

`ynh_setup_source --dest_dir="$install_dir" --full_replace=1 --keep="app/config/parameters.yml var/logs"` should also keep `web/assets/images` I guess

**Comment by Salamandar** [comment]
Was fixed by #204 . Sorry for the inconvenience.
