### ISSUE TITLE
Can’t install wallabag2/Installation fails

### ISSUE THREAD

**Issue by numberdotone** [YunoHost-Apps/wallabag2_ynh#21]
I tried to reinstall Wallabag 2 due to the failing Pocket import using https://github.com/YunoHost-Apps/wallabag2_ynh/ but something is going wrong. It was working before I made a dist-upgrade yesterday to YNH 2.5.
It ends up here:

>delete mode 120000 php5/fpm/conf.d/20-tidy.ini
delete mode 120000 php5/cli/conf.d/20-tidy.ini
2 files changed, 2 deletions(-)
Author: admin 
[master c02345f] committing changes in /etc after apt run
Processing triggers for libc-bin (2.19-18+deb8u7) ...
insserv: warning: current stop runlevel(s) (0 6) of script `php5-fpm' overrides LSB defaults (0 1 6).
insserv: warning: current stop runlevel(s) (0 6) of script `php5-fpm' overrides LSB defaults (0 1 6).
insserv: warning: script is corrupt or invalid: /etc/init.d/../rc0.d/K01yunohost-api
Processing triggers for php5-fpm (5.6.29+dfsg-0+deb8u1) ...
Removing libtidy-0.99-0 (20091223cvs-1.4+deb8u1) ...
php5_invoke prerm: Disable module tidy for fpm SAPI
php5_invoke prerm: Disable module tidy for cli SAPI
Removing php5-tidy (5.6.29+dfsg-0+deb8u1) ...
Removing wallabag-deps (2.1-1) ...
(Reading database ... (Reading database ... 5% (Reading database ... 10% (Reading database ... 15% (Reading database ... 20% (Reading database ... 25% (Reading database ... 30% (Reading database ... 35% (Reading database ... 40% (Reading database ... 45% (Reading database ... 50% (Reading database ... 55% (Reading database ... 60% (Reading database ... 65% (Reading database ... 70% (Reading database ... 75% (Reading database ... 80% (Reading database ... 85% (Reading database ... 90% (Reading database ... 95% (Reading database ... 100% (Reading database ... 44723 files and directories currently installed.)
1 file changed, 2 insertions(+)
Author: admin 
[master d95df1a] saving uncommitted changes in /etc prior to apt run

> + sudo apt-get -y -qq autoremove wallabag-deps
> + DEBIAN_FRONTEND=noninteractive
> + ynh_apt autoremove wallabag-deps
> + ynh_package_autoremove wallabag-deps
> + sudo service nginx reload
> + sudo service php5-fpm restart
> + sudo rm -f /etc/nginx/conf.d/www.example.de.d/wallabag2.conf
> + [[ -n www.example.de ]]
> + sudo rm -f /etc/php5/fpm/pool.d/wallabag2.conf
> + sudo rm -rf /var/www/wallabag2
> + domain=www.example.de
> ++ sudo yunohost app setting wallabag2 domain --output-as plain --quiet
> ++ ynh_app_setting_get wallabag2 domain
> + mysql -u root --password=g7vK9TFrTE -B ''
> + ynh_mysql_connect_as root g7vK9TFrTE ''
> ++ sudo cat /etc/yunohost/mysql
> + ynh_mysql_execute_as_root 'DROP USER '\''wallabag2'\''@'\''localhost'\'';'
> + ynh_mysql_drop_user wallabag2
> + mysql -u root --password=g7vK9TFrTE -B ''
> + ynh_mysql_connect_as root g7vK9TFrTE ''
> ++ sudo cat /etc/yunohost/mysql
> + ynh_mysql_execute_as_root 'DROP DATABASE wallabag2;'
> + ynh_mysql_drop_db wallabag2
> + dbuser=wallabag2
> + dbname=wallabag2
> +++ . /usr/share/yunohost/helpers.d/utils
> +++ '[' -r /usr/share/yunohost/helpers.d/utils ']'
> +++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
> +++ . /usr/share/yunohost/helpers.d/user
> +++ '[' -r /usr/share/yunohost/helpers.d/user ']'
> +++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
> +++ . /usr/share/yunohost/helpers.d/string
> +++ '[' -r /usr/share/yunohost/helpers.d/string ']'
> +++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
> +++ . /usr/share/yunohost/helpers.d/setting
> +++ '[' -r /usr/share/yunohost/helpers.d/setting ']'
> +++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
> +++ . /usr/share/yunohost/helpers.d/print
> +++ '[' -r /usr/share/yunohost/helpers.d/print ']'
> +++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
> +++ . /usr/share/yunohost/helpers.d/package
> +++ '[' -r /usr/share/yunohost/helpers.d/package ']'
> +++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
> ++++ MYSQL_ROOT_PWD_FILE=/etc/yunohost/mysql
> +++ . /usr/share/yunohost/helpers.d/mysql
> +++ '[' -r /usr/share/yunohost/helpers.d/mysql ']'
> +++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
> +++ . /usr/share/yunohost/helpers.d/ip
> +++ '[' -r /usr/share/yunohost/helpers.d/ip ']'
> +++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
> ++++ CAN_BIND=1
> +++ . /usr/share/yunohost/helpers.d/filesystem
> +++ '[' -r /usr/share/yunohost/helpers.d/filesystem ']'
> +++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
> ++++ run-parts --list /usr/share/yunohost/helpers.d
> ++ . /usr/share/yunohost/helpers
> ++ PKGDIR=/var/cache/yunohost/from_file/wallabag2_ynh-master
> +++ pwd
> +++ cd ../
> ++ WALLABAG_SOURCE_SHA256=eb64205a4d7c161527edd08bed22e8dd9799fe8a4130c5964c18cba3a94c9768
> ++ WALLABAG_SOURCE_URL=https://framabag.org/wallabag-release-2.1.4.tar.gz
> ++ DEPS_PKG_NAME=wallabag-deps
> ++ VERSION=2.1.4
> + . ./_common.sh
> + app=wallabag2
> script '/var/cache/yunohost/from_file/wallabag2_ynh-master/scripts/remove' will be executed...
> + cd /var/www/wallabag2
> + shift 2
> ./_common.sh: line 48: cd: /var/www/wallabag2: Permission denied
> + local WORKDIR=/var/www/wallabag2
> + local AS_USER=www-data
> + exec_console www-data /var/www/wallabag2 wallabag:install
> + sudo chown -R www-data: /var/www/wallabag2
> + sudo mv /tmp/tmp.N9GiaDZLje /var/www/wallabag2
> + sed -i 's@{DESKEY}@jA0rPnNmcrZ47u93wekI8yr8@g' /tmp/tmp.N9GiaDZLje/app/config/parameters.yml
> + sed -i 's@{DBPASS}@DmJpJ4QTYVbI62KoNWSavRk0@g' /tmp/tmp.N9GiaDZLje/app/config/parameters.yml
> + sed -i 's@{DBUSER}@wallabag2@g' /tmp/tmp.N9GiaDZLje/app/config/parameters.yml
> + sed -i 's@{DBNAME}@wallabag2@g' /tmp/tmp.N9GiaDZLje/app/config/parameters.yml
> + cp ../conf/parameters.yml /tmp/tmp.N9GiaDZLje/app/config/parameters.yml
> + wb_conf=/tmp/tmp.N9GiaDZLje/app/config/parameters.yml
> + mysql -u root --password=g7vK9TFrTE -B ''
> + ynh_mysql_connect_as root g7vK9TFrTE ''
> ++ sudo cat /etc/yunohost/mysql
> + ynh_mysql_execute_as_root 'CREATE DATABASE wallabag2; GRANT ALL PRIVILEGES ON wallabag2.* TO '\''wallabag2'\''@'\''localhost'\'' IDENTIFIED BY '\''DmJpJ4QTYVbI62KoNWSavRk0'\'' WITH GRANT OPTION;'
> + sql+=' WITH GRANT OPTION;'
> + sql+=' IDENTIFIED BY '\''DmJpJ4QTYVbI62KoNWSavRk0'\'''
> + [[ -n DmJpJ4QTYVbI62KoNWSavRk0 ]]
> + sql+=' GRANT ALL PRIVILEGES ON wallabag2.* TO '\''wallabag2'\''@'\''localhost'\'''
> + [[ 3 -gt 1 ]]
> + sql='CREATE DATABASE wallabag2;'
> + db=wallabag2
> + ynh_mysql_create_db wallabag2 wallabag2 DmJpJ4QTYVbI62KoNWSavRk0
> + sudo yunohost app setting wallabag2 deskey -v jA0rPnNmcrZ47u93wekI8yr8 --quiet
> + ynh_app_setting_set wallabag2 deskey jA0rPnNmcrZ47u93wekI8yr8
> + sudo yunohost app setting wallabag2 mysqlpwd -v DmJpJ4QTYVbI62KoNWSavRk0 --quiet
> + ynh_app_setting_set wallabag2 mysqlpwd DmJpJ4QTYVbI62KoNWSavRk0
> + dbpass=DmJpJ4QTYVbI62KoNWSavRk0
> ++ dd if=/dev/urandom bs=1 count=200
> ++ sed -n 's/\(.\{24\}\).*/\1/p'
> ++ tr -c -d A-Za-z0-9
> ++ ynh_string_random
> + deskey=jA0rPnNmcrZ47u93wekI8yr8
> ++ sed -n 's/\(.\{24\}\).*/\1/p'
> ++ dd if=/dev/urandom bs=1 count=200
> ++ tr -c -d A-Za-z0-9
> ++ ynh_string_random 24
> patching file src/Wallabag/YunoHostBundle/Security/LogoutSuccessHandler.php
> Hunk #1 succeeded at 43 (offset 6 lines).
> patching file app/config/services.yml
> Hunk #1 succeeded at 62 (offset 2 lines).
> patching file app/config/security.yml
> + patch -p1
> + for p in '${PKGDIR}/patches/*.patch'
> Hunk #2 succeeded at 46 (offset 2 lines).
> Hunk #1 succeeded at 13 with fuzz 1 (offset 2 lines).
> patching file app/config/security.yml
> Hunk #1 succeeded at 42 (offset 6 lines).
> patching file app/config/services.yml
> + patch -p1
> + for p in '${PKGDIR}/patches/*.patch'
> + cd /tmp/tmp.N9GiaDZLje
> + rm -f /tmp/wallabag.tar.gz
> ++ tar xf /tmp/wallabag.tar.gz -C /tmp/tmp.N9GiaDZLje --strip-components 1
> + eval tar xf /tmp/wallabag.tar.gz -C /tmp/tmp.N9GiaDZLje --strip-components 1
> + [[ admin = admin ]]
> ++ whoami
> + shift 1
> + local USER=admin
> + exec_as admin tar xf /tmp/wallabag.tar.gz -C /tmp/tmp.N9GiaDZLje --strip-components 1
> + echo 'eb64205a4d7c161527edd08bed22e8dd9799fe8a4130c5964c18cba3a94c9768 /tmp/wallabag.tar.gz'
> + sha256sum -c
> + wget -q -O /tmp/wallabag.tar.gz https://framabag.org/wallabag-release-2.1.4.tar.gz
> + rm -f /tmp/wallabag.tar.gz
> + wb_tarball=/tmp/wallabag.tar.gz
> + local AS_USER=admin
> + local DESTDIR=/tmp/tmp.N9GiaDZLje
> + extract_wallabag /tmp/tmp.N9GiaDZLje
> + TMPDIR=/tmp/tmp.N9GiaDZLje
> ++ mktemp -d
> ++ echo 'This helper is deprecated, you should use '\''mktemp -d'\'' instead.'
> This helper is deprecated, you should use 'mktemp -d' instead.
> ++ ynh_mkdir_tmp
> + dpkg-query -W -f '${Status}' wallabag-deps
> + grep -c 'ok installed'
> + ynh_package_is_installed wallabag-deps
> + rm -rf /tmp/tmp.NsundPte4T
> + [[ -n /tmp/tmp.NsundPte4T ]]
> create mode 120000 php5/fpm/conf.d/20-tidy.ini
> create mode 120000 php5/cli/conf.d/20-tidy.ini
> 2 files changed, 2 insertions(+)
> Author: admin 
> [master 202f20b] committing changes in /etc after apt run
> insserv: warning: current stop runlevel(s) (0 6) of script `php5-fpm' overrides LSB defaults (0 1 6).
> insserv: warning: current stop runlevel(s) (0 6) of script `php5-fpm' overrides LSB defaults (0 1 6).
> insserv: warning: script is corrupt or invalid: /etc/init.d/../rc0.d/K01yunohost-api
> Processing triggers for php5-fpm (5.6.29+dfsg-0+deb8u1) ...
> Processing triggers for libc-bin (2.19-18+deb8u7) ...
> php5_invoke: Enable module tidy for fpm SAPI
> php5_invoke: Enable module tidy for cli SAPI
> debconf: falling back to frontend: Readline
> debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
> debconf: unable to initialize frontend: Dialog
> Setting up php5-tidy (5.6.29+dfsg-0+deb8u1) ...
> Setting up libtidy-0.99-0 (20091223cvs-1.4+deb8u1) ...
> insserv: warning: current stop runlevel(s) (0 6) of script `php5-fpm' overrides LSB defaults (0 1 6).
> insserv: warning: current stop runlevel(s) (0 6) of script `php5-fpm' overrides LSB defaults (0 1 6).
> insserv: warning: script is corrupt or invalid: /etc/init.d/../rc0.d/K01yunohost-api
> Processing triggers for php5-fpm (5.6.29+dfsg-0+deb8u1) ...
> Unpacking php5-tidy (5.6.29+dfsg-0+deb8u1) ...
> Preparing to unpack .../php5-tidy_5.6.29+dfsg-0+deb8u1_armhf.deb ...
> Selecting previously unselected package php5-tidy.
> Unpacking libtidy-0.99-0 (20091223cvs-1.4+deb8u1) ...
> Preparing to unpack .../libtidy-0.99-0_20091223cvs-1.4+deb8u1_armhf.deb ...
> (Reading database ... (Reading database ... 5% (Reading database ... 10% (Reading database ... 15% (Reading database ... 20% (Reading database ... 25% (Reading database ... 30% (Reading database ... 35% (Reading database ... 40% (Reading database ... 45% (Reading database ... 50% (Reading database ... 55% (Reading database ... 60% (Reading database ... 65% (Reading database ... 70% (Reading database ... 75% (Reading database ... 80% (Reading database ... 85% (Reading database ... 90% (Reading database ... 95% (Reading database ... 100% (Reading database ... 44711 files and directories currently installed.)
> Selecting previously unselected package libtidy-0.99-0.
> dpkg-preconfigure: unable to re-open stdin:
> debconf: falling back to frontend: Teletype
> debconf: (This frontend requires a controlling tty.)
> debconf: unable to initialize frontend: Readline
> debconf: falling back to frontend: Readline
> debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
> debconf: unable to initialize frontend: Dialog
> 1 file changed, 1 insertion(+), 3 deletions(-)
> Author: admin 
> [master 252beea] saving uncommitted changes in /etc prior to apt run
> + sudo apt-get -y -qq -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold install -f
> + DEBIAN_FRONTEND=noninteractive
> + ynh_apt -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold install -f
> + ynh_package_install -f
> Setting up wallabag-deps (2.1-1) ...
> Package php5-tidy is not installed.
> wallabag-deps depends on php5-tidy; however:
> dpkg: wallabag-deps: dependency problems, but configuring anyway as you requested:
> Unpacking wallabag-deps (2.1-1) ...
> Preparing to unpack ./wallabag-deps_2.1-1_all.deb ...
> (Reading database ... 44707 files and directories currently installed.)
> Selecting previously unselected package wallabag-deps.
> + sudo dpkg --force-depends -i ./wallabag-deps_2.1-1_all.deb
> dh_installdeb: Compatibility levels before 9 are deprecated (level 7 in use)
> dh_installchangelogs: Compatibility levels before 9 are deprecated (level 7 in use)
> dh_installdocs: Compatibility levels before 9 are deprecated (level 7 in use)
> dh_install: Compatibility levels before 9 are deprecated (level 7 in use)
> + equivs-build ./control
> + cd /tmp/tmp.NsundPte4T
> + cp ../conf/wallabag-deps.control /tmp/tmp.NsundPte4T/control
> + TMPDIR=/tmp/tmp.NsundPte4T
> This helper is deprecated, you should use 'mktemp -d' instead.
> ++ mktemp -d
> ++ echo 'This helper is deprecated, you should use '\''mktemp -d'\'' instead.'
> ++ ynh_mkdir_tmp
> + sudo apt-get -y -qq update
> + DEBIAN_FRONTEND=noninteractive
> + ynh_apt update
> + ynh_package_update
> + [[ -z 2.1-1 ]]
> + [[ -z wallabag-deps ]]
> + pkgversion=2.1-1
> ++ cut '-d ' -f 2
> ++ grep '^Version: ' ../conf/wallabag-deps.control
> + pkgname=wallabag-deps
> ++ cut '-d ' -f 2
> ++ grep '^Package: ' ../conf/wallabag-deps.control
> + grep -c 'ok installed'
> + dpkg-query -W -f '${Status}' equivs
> + ynh_package_is_installed equivs
> + controlfile=../conf/wallabag-deps.control
> + ynh_package_install_from_equivs ../conf/wallabag-deps.control
> + [[ -d /var/www/wallabag2 ]]
> + DESTDIR=/var/www/wallabag2
> + sudo yunohost app setting wallabag2 admin_user -v alex --quiet
> + ynh_app_setting_set wallabag2 admin_user alex
> + sudo yunohost user list --output-as json
> + grep -q '"username": "alex"'
> + ynh_user_exists alex
> + sudo yunohost app checkurl www.example.de/wallabag -a wallabag2
> + dbuser=wallabag2
> + dbname=wallabag2
> +++ . /usr/share/yunohost/helpers.d/utils
> +++ '[' -r /usr/share/yunohost/helpers.d/utils ']'
> +++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
> +++ . /usr/share/yunohost/helpers.d/user
> +++ '[' -r /usr/share/yunohost/helpers.d/user ']'
> +++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
> +++ . /usr/share/yunohost/helpers.d/string
> +++ '[' -r /usr/share/yunohost/helpers.d/string ']'
> +++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
> +++ . /usr/share/yunohost/helpers.d/setting
> +++ '[' -r /usr/share/yunohost/helpers.d/setting ']'
> +++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
> +++ . /usr/share/yunohost/helpers.d/print
> +++ '[' -r /usr/share/yunohost/helpers.d/print ']'
> +++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
> +++ . /usr/share/yunohost/helpers.d/package
> +++ '[' -r /usr/share/yunohost/helpers.d/package ']'
> +++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
> ++++ MYSQL_ROOT_PWD_FILE=/etc/yunohost/mysql
> +++ . /usr/share/yunohost/helpers.d/mysql
> +++ '[' -r /usr/share/yunohost/helpers.d/mysql ']'
> +++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
> +++ . /usr/share/yunohost/helpers.d/ip
> +++ '[' -r /usr/share/yunohost/helpers.d/ip ']'
> +++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
> ++++ CAN_BIND=1
> +++ . /usr/share/yunohost/helpers.d/filesystem
> +++ '[' -r /usr/share/yunohost/helpers.d/filesystem ']'
> +++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
> ++++ run-parts --list /usr/share/yunohost/helpers.d
> ++ . /usr/share/yunohost/helpers
> ++ PKGDIR=/var/cache/yunohost/from_file/wallabag2_ynh-master
> +++ pwd
> +++ cd ../
> ++ WALLABAG_SOURCE_SHA256=eb64205a4d7c161527edd08bed22e8dd9799fe8a4130c5964c18cba3a94c9768
> ++ WALLABAG_SOURCE_URL=https://framabag.org/wallabag-release-2.1.4.tar.gz
> ++ DEPS_PKG_NAME=wallabag-deps
> ++ VERSION=2.1.4
> + source ./_common.sh
> + admin=alex
> + path=/wallabag
> + domain=www.example.de
> + app=wallabag2
> + set -eu
> script '/var/cache/yunohost/from_file/wallabag2_ynh-master/scripts/install' will be executed ...
> Checking required packages...
> Done.
> Unzip...
> Download ...

_edit: I took the liberty to edit your post and make the log quoted - it's easier to read :)_

Any ideas?

**Comment by lapineige** [comment]
So it stops at the Download line ? Without any other message ?
Is your ssh connection still active at this time ?

What does `yunohost app list -i | grep wallabag` says ?

**Comment by numberdotone** [comment]
Sorry for the missing explanation. I put the github link into the field under applications > install user defined app (or however it is called in English ;-). After provide the information about URL (/wallabag), domain (example.de), admin (alex) it starts responding with "Download ..." and end at the top "delete mode ..." (the sort is here ascending contrary to the normal terminal). It stops with a message "Installation failed" (isn`t c&p here).
During the installation your command returns a "id: wallabag2" and when the installation fails: nothing

**Comment by lapineige** [comment]
Could you test using the command line ?
`yunohost app install https://github.com/YunoHost-Apps/wallabag2_ynh --verbose` (verbose is here to have a ... verbose output)

> (the sort is here ascending contrary to the normal terminal)

That's normal, so the latest line is always at the same position.

> During the installation your command returns a "id: wallabag2" and when the installation fails: nothing

The command just test if yunohost consider wallabag2 to be installed. (the `-i` option shows the installed apps only)
So it's the normal behavior when encountering an error, removing all the stuff in order not to break your Yunohost.

**Comment by lapineige** [comment]
Ok, spotted the error: 
> ./_common.sh: line 48: cd: /var/www/wallabag2: Permission denied

I have the same issue on my side. Something doesn't work in this line.

**Comment by numberdotone** [comment]
As I'm not a developer I can't really help but reading the lines the user www-data should change the directory to "/var/www/wallabag2". And somethings going wrong with "shift 2" (I tried to understand which parameter should be deleted but I even don't know which values they had before)
If I talk nonsense please be patient with me.

**Comment by lapineige** [comment]
I still didn't figure out what `shift 2` is doing. But playing with the code, it seems like the issue is somewhere else.
It seems to be in this line: https://github.com/YunoHost-Apps/wallabag2_ynh/blob/master/scripts/_common.sh#L49 (in fact it's the same line as line 48, but this part is blocking)
But I still don't know how to solve that. Sounds like it's a general install issue. Maybe because of Yunohost 2.5.
Related issue: https://github.com/YunoHost-Apps/wallabag2_ynh/issues/19#issuecomment-278188438

> If I talk nonsense please be patient with me.

Don't worry,  it's new for me too :)

**Comment by lapineige** [comment]
Just to be sure it's not coming from my side, could you test this version ?
https://github.com/lapineige/wallabag2_ynh/tree/lapineige-patch-1
(I'm not sure the web interface allows you to do that, if not try with the command line)

**Comment by numberdotone** [comment]
Web interface doesn't work, cli tells

lapineige-patch-1: line 5: syntax error near unexpected token `newline'
lapineige-patch-1: line 5: `<!DOCTYPE html>'

**Comment by lapineige** [comment]
Uh... strange error, I didn't have this one.
Could you try again now ?
If it works, please tell me if wallabag is working correctly (not the case on my side)

**Comment by numberdotone** [comment]
While I'm more that point-and-click guy ;-) it took me a moment to find out the right way to use the terminal. And here's the result:

root@machine:~# yunohost app install https://github.com/lapineige/wallabag2_ynh/tree/lapineige-patch-1
Available domains:
- example.de
- www.example.de
Choose a domain for Wallabag (default: www.example.de): www.example.de
Choose a path for Wallabag (default: /wallabag): /wallabag
Choose the Wallabag administrator: alex
Warning: This helper is deprecated, you should use 'mktemp -d' instead.
Warning: dh_install: Compatibility levels before 9 are deprecated (level 7 in use)
Warning: dh_installdocs: Compatibility levels before 9 are deprecated (level 7 in use)
Warning: dh_installchangelogs: Compatibility levels before 9 are deprecated (level 7 in use)
Warning: dh_installdeb: Compatibility levels before 9 are deprecated (level 7 in use)
Warning: This helper is deprecated, you should use 'mktemp -d' instead.
Warning: tar: Ignoring unknown extended header keyword 'SCHILY.dev'
Warning: tar: Ignoring unknown extended header keyword 'SCHILY.ino'
Warning: tar: Ignoring unknown extended header keyword 'SCHILY.nlink'
Success! The SSOwat configuration has been generated
Success! Installation complete
root@machine:~#

So, it's working now. Thanks a lot for your work and your support.

**Comment by lapineige** [comment]
@numberdotone is it really working ? I mean, can you for instance import an article ?
On my side I can't, even if install works.
(but by the way I'm trying with 2.2.1, maybe there are some other issues related to this version)

**Comment by numberdotone** [comment]
@lapineige You are right, creating entries will result in "no title found" entries without any links, import reports:
500: Internal Server Error

Catchable Fatal Error: Argument 2 passed to Wallabag\CoreBundle\GuzzleSiteAuthenticator\GrabySiteConfigBuilder::__construct() must be of the type array, null given, called in /var/www/wallabag2/var/cache/prod/appProdProjectContainer.php on line 6340 and defined

I will deinstall and try it again with the verbose command, just to see what happens then

**Comment by lapineige** [comment]
For version 2.1.4, @naguirre fixed this issue in a more clever way. I just merged his commit, so you can install wallabag from this repo again :)
Thanks @naguirre ! :)
