### ISSUE TITLE
Can't import v1 json

### ISSUE THREAD

**Issue by roylockhart** [YunoHost-Apps/wallabag2_ynh#3]
Hi guys, I can't manage to import v1's articles. I think that my json is clean because I can import it in wallabag 1.92.  
Looks like the connection broke or something. I can replicate this on chromium and safari.

<img width="626" alt="capture d ecran 2016-07-21 a 12 35 09" src="https://cloud.githubusercontent.com/assets/10902805/17020016/aa45a9e0-4f3f-11e6-8209-ae7b47606f4f.png">

**Comment by lapineige** [comment]
I had an issue when importing with no article. Try to add one before importing, and see if it's working after that.

**Comment by jeromelebleu** [comment]
Seems that #4 duplicates this one... I'll close it as it seems to be a Wallabag issue. Please check if this bug has not been fixed yet and no issue is talking about that [there](https://github.com/wallabag/wallabag/issues) - and open a new issue if not. Thanks!
