### ISSUE TITLE
Update impossible (from master)

### ISSUE THREAD

**Issue by klorydryk** [YunoHost-Apps/wallabag2_ynh#32]
I tried to update my version of Wallabag from Master to branch code_refactoring:
'sudo yunohost --verbose app upgrade wallabag2 -u https://github.com/YunoHost-Apps/wallabag2_ynh/tree/code_refactoring'
But the result is:
'Erreur : Impossible de mettre à jour wallabag2
Erreur : Aucune application à mettre à jour'
Is it really impossible? How can I do?

**Comment by lapineige** [comment]
Could you try again with the `--verbose` option ?

Does it fail after this line: `sudo yunohost backup create --ignore-hooks --apps wallabag2 --name wallabag2-pre-upgrade1`, saying there is nothing to backup ?

**Comment by klorydryk** [comment]
Yes

**Comment by JimboJoe** [comment]
I've just pushed a fix: I had introduced a prior backup in upgrade script (a new good practice), but as current Wallabag2 instances don't have backup feature, it generated an error.
Now the prior backup is conditioned to the backup feature existence.

**Comment by klorydryk** [comment]
Ok, it works, thanks!

**Comment by lapineige** [comment]
Same for me, thanks @JimboJoe :)
