### ISSUE TITLE
Article assets don't have the right URL so are not visible

### ISSUE THREAD

**Issue by arthurlutz** [YunoHost-Apps/wallabag2_ynh#35]
On articles that have a photo the following html is used (the app is served on domain.com/wallabag/)

```
<div class="preview activator" style="background-image: url(/assets/images/2/6/26ddd99c/e333994e.jpeg)"></div>
```

Changing the URL to ```/wallabag/assets/images/2/6/26ddd99c/e333994e.jpeg``` gets the image to show.

**Comment by lapineige** [comment]
So I guess you're using the option to locally store the images ?

Which Wallabag's version are you using ?
