### ISSUE TITLE
error while importing 

### ISSUE THREAD

**Issue by anmol26s** [YunoHost-Apps/wallabag2_ynh#4]
I see error message on Starred ,Archived , unread and while importing the json file from the previous version.

```
Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

```

**Comment by lapineige** [comment]
I fixed this issue by adding one article. Could you try it ?

A similar one here #3

**Comment by anmol26s** [comment]
I can not add the article too. Its giving the me same error on entering the url and hitting the enter for adding the article.

**Comment by tcitworld** [comment]
@anmol26s  Please report on the main wallabag repo and tell us which article is giving you this trouble.

**Comment by jeromelebleu** [comment]
As said by @tcitworld - thanks by the way for looking at this repo! - please report upstream bugs on the wallabag repo, if no one already exist. Thanks!
