### ISSUE TITLE
Redis permission problem

### ISSUE THREAD

**Issue by solarus0** [YunoHost-Apps/wallabag2_ynh#46]
Hi everyone

According to the Lynis Audit tool, the permission for /etc/redis/redis.conf should be 640 and not 644.

 ! Redis configuration file /etc/redis/redis.conf is world readable and might leak sensitive details [DBS-1882]
    - Details  : /etc/redis/redis.conf
    - Solution : Use chmod 640 to change file permissions
      https://cisofy.com/controls/DBS-1882/

Can you fix that in your package ?
Thanks a lot.

**Comment by JimboJoe** [comment]
Hello,
I'm not sure how your issue is related to this package... redis configuration is setup by YunoHost itself, so your issue would be more relevant here https://dev.yunohost.org ;-)
By the way, I can't seem to reproduce your issue on my YunoHost servers: my /etc/redis/redis.conf rights are 640
