### ISSUE TITLE
Unable to install the app

### ISSUE THREAD

**Issue by ramakirankumar** [YunoHost-Apps/wallabag2_ynh#47]
Hi,
[yunohost_wallbaglog.txt](https://github.com/YunoHost-Apps/wallabag2_ynh/files/1708714/yunohost_wallbaglog.txt)

The installation of this got failed. I could see few errors like error with wallabag2 app and also invalid folder path (the path contains an extra space).

Attached is the log for reference.

**Comment by JimboJoe** [comment]
Could you please try executing `apt-get install php5-ldap` and retry the installation?

**Comment by ramakirankumar** [comment]
Thanks. Installation was successful.
