### ISSUE TITLE
Cache cleanup required after "Change URL" operation

### ISSUE THREAD

**Issue by manuelleduc** [YunoHost-Apps/wallabag2_ynh#48]
Hello,

I recently changed my wallabag2 application from mydomain.tdl/wallabag to wallabag.mydomain.tld using the "Change URL" operation.

It went well but some assets such as the css and js files where not served when accessing wallabag.mydomain.tld (302 errors due to SSO redirection since the previous urls where pointing to protected paths).

I fixed the issue by removing the /var/www/wallabag2/var/cache/ directory.

Happing to give more details if needed.

Sincrely

Manuel

**Comment by lapineige** [comment]
Thank you for the report :)
Is that the only operation you made ?

**Comment by manuelleduc** [comment]
As it definitely not a brand new instance I can't certify that this is not caused by some older modification.

But to answer your question, apart from updating yunohost regularly, using the "Change URL" operation was the only thing I did during the last week.

**Comment by lapineige** [comment]
Fixed
