### ISSUE TITLE
missing system requirements

### ISSUE THREAD

**Issue by ilupo** [YunoHost-Apps/wallabag2_ynh#49]
Hello,

update failed, now i cant install wallabag

cant install wallabag2 - got error "Missing System requirements"

  PDO Driver (pdo_mysql)   ERROR!   Database driver "pdo_mysql" is not installed.
  Database connection      ERROR!   Can't connect to the database: An exception occured in driver: could not find driver
  Database version         OK!
  curl_exec                ERROR!   You need the curl_exec function activated
  curl_multi_init          ERROR!   You need the curl_multi_init function activated
 ------------------------ -------- -----------

```
[console] Error thrown while running command "--no-interaction --env=prod wallabag:install". Message: "Some system requirements are not fulfilled. Please check output messages and fix them." ["error" => RuntimeException { …},"command" => "--no-interaction --env=prod wallabag:install","message" => "Some system requirements are not fulfilled. Please check output messages and fix them."] []
```
----------------------------------------------------------------------

thanks for help....

**Comment by denisasche87** [comment]
I have th Same Issue on Wallabag2 Installation. My YunoHost Verson is 2.7.14.5.

Wallabag installer
==================

Step 1 of 4: Checking system requirements.
------------------------------------------

 ------------------------ -------- --------------------------------------------------------------------------------------
  Checked                  Status   Recommendation
 ------------------------ -------- --------------------------------------------------------------------------------------
  PDO Driver (pdo_mysql)   ERROR!   Database driver "pdo_mysql" is not installed.
  Database connection      ERROR!   Can't connect to the database: An exception occured in driver: could not find driver
  Database version         OK!
  curl_exec                ERROR!   You need the curl_exec function activated
  curl_multi_init          ERROR!   You need the curl_multi_init function activated
 ------------------------ -------- --------------------------------------------------------------------------------------

**Comment by lapineige** [comment]
Do you still have the issue ?

**Comment by lapineige** [comment]
Ok, I have the same issue, Yunohost 3.4.

I'm on a VPS with LXC container. Maybe there is a link ? @ilupo and @denisasche87 on which kind of server do you try to install wallabag ?

**Comment by lapineige** [comment]
up :)
