### ISSUE TITLE
Update to 2.0.7

### ISSUE THREAD

**Issue by lapineige** [YunoHost-Apps/wallabag2_ynh#5]
@jeromelebleu could you update to the 2.0.7 version ? The wallabag team released it a few days ago: https://www.wallabag.org/blog/2016/08/22/wallabag-207

This version, and the previous ones from 2.0 (the current version of this repo, right ?), fix a lot of small but annoying bugs.
It would be great if you have some time to work on this. Thanks :)
(If you need some tests/help, feel free to ping me ;)

**Comment by jeromelebleu** [comment]
Hi @lapineige, thanks for the information! It's done with https://github.com/YunoHost-Apps/wallabag2_ynh/commit/cd90613f6d70ab0ef077a16bf78f3b5516810812, feel free to try it and give any feedbacks!

**Comment by lapineige** [comment]
:-o :-o :-o
Is it Christmas today ? Because it's not my birthday ^^

Thanks a lot, trying right now.

**Comment by lapineige** [comment]
Done, everything is working right now :)
