### ISSUE TITLE
Moving from PHP5 to PHP7

### ISSUE THREAD

**Issue by jodumont** [YunoHost-Apps/wallabag2_ynh#62]
Since Yunohost on Debian9 use PHP7 by default
and it's an easy way to improve the performance
I'll would like to see this apps using PHP 7.x instead of PHP 5

I say that because I see [php5](https://github.com/YunoHost-Apps/wallabag2_ynh/blob/master/conf/nginx.conf#L21) mentioned in your config file

**Comment by JimboJoe** [comment]
YunoHost has been providing PHP7 instead of PHP5 since version 3.0 (Debian Stretch). Some explicit mentions to php5 still remain in some apps, but a mechanism had been introduce in YunoHost to ensure compatibility with these apps (force use of PHP7).
