### ISSUE TITLE
wallabag/android-app does not work: 500 Error

### ISSUE THREAD

**Issue by rocky-III** [YunoHost-Apps/wallabag2_ynh#73]
i´m using the yunohost Wallbag2 installation with the android app

https://f-droid.org/de/packages/fr.gaulupeau.apps.InThePoche/

It used to work but since few weeks I get this error message 

`com.di72nn.stuff.wallabag.apiwrapper.exceptions.unsuccessfulResponseException: HTTP response: 500 Internal Server Error `

I tried this

https://github.com/wallabag/android-app/issues/757

but it did not wok.
What ells could I try? Thanks for your help

**Comment by rocky-III** [comment]
under: 
/var/log/nginx/wallabag-access.log

I find this

"POST /api/entries.json HTTP/2.0" 500 540 "-" "okhttp/3.14.2"

**Comment by lapineige** [comment]
Hum, I don't know what's going on…
What's your wallabag version ? 2.3.5 ?

Do you have some more detailed log (as provided in the issue, for instance ?).

**Comment by rocky-III** [comment]
Hi lapineige,
I´m on 2.3.8~ynh1
Where could I look for more logs in yunohost?

**Comment by rocky-III** [comment]
hmmm...  just did an reinall of the  android app and now it is working again... don´t konw what was going on...

**Comment by lapineige** [comment]
Ok, that's strange… I'm closing, don't hesitate to reopen if needed ;)
