### ISSUE TITLE
Upgrade this package to "high_quality" tag 

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost-Apps/wallabag2_ynh#75]
Hi

Following that announce, https://forum.yunohost.org/t/about-the-end-of-official-apps-in-yunohost/10530, this app won't be official anymore.
This app currently has the tag `high_quality` as a former official app. As this status will be dropped, to keep this tag, the maintainer of this app has to officially ask for the tag.
To do so, please follow those [instructions](https://github.com/YunoHost/apps#how-to-make-my-app-a-high-quality-app-).

**Comment by lapineige** [comment]
Thanks for those information.
With my current available time and knowledge, I don't think I'll try to stick to that tag rules. Level 7 is fair enough for me right now.

But I'll be happy if anyone want to work on this.

**Comment by maniackcrudelis** [comment]
Ok.
You may be interested by the tag `request_help` for this app then.
Have a look to https://github.com/YunoHost/apps#what-to-do-if-i-cant-maintain-my-app-anymore- for more information if you're interested.

**Comment by lapineige** [comment]
I'm maintaining it, but I don't think I'll go to level 8.
