### ISSUE TITLE
Runtime Exception: Unable to write in the cache dir

### ISSUE THREAD

**Issue by scharc** [YunoHost-Apps/wallabag2_ynh#78]
the post_user_create hook is not working on ynh 3.7.0 anymore...

**Comment by kay0u** [comment]
Hi,

It should be fixed by: https://github.com/YunoHost-Apps/wallabag2_ynh/pull/76

You can upgrade an test it with:
```
sudo yunohost app upgrade wallabag2 -u https://github.com/YunoHost-Apps/wallabag2_ynh/tree/testing --debug
```

**Comment by scharc** [comment]
https://paste.yunohost.org/tomufoxaqi
BUT if I manually edit the post_hook files and replace www_data with the wallabag2 user it is working.

**Comment by kay0u** [comment]
Thank you for the feedback, it should be fixed now

**Comment by scharc** [comment]
That was a very very very quick fix. Thank you!
