### ISSUE TITLE
error while creating rss token

### ISSUE THREAD

**Issue by bachy** [YunoHost-Apps/wallabag2_ynh#8]
The server returned a "500 Internal Server Error".

can't find any log about this :( (php5-fpm.log, mydomain-error.log, nginx/error.log)

**Comment by bachy** [comment]
ok this solution worked for me : https://forum.yunohost.org/t/wallabag-v2-integration-dans-yunohost/1453/30
just fill the items per page setting, then you'll be able to generate the token

**Comment by jeromelebleu** [comment]
It seems to be an upstream issue and not a YunoHost app's one... Could you report it [here](https://github.com/wallabag/wallabag/issues) if no one already exist please? I would prefer to not have to patch Wallabag to fix those kind of bugs... I'll close it meanwhile.
