### ISSUE TITLE
Failed upgrade: unbound variable ./upgrade: line 184: wb_conf

### ISSUE THREAD

**Issue by kuba-orlik** [YunoHost-Apps/wallabag2_ynh#83]
I've tried running the upgrade but it failed with the message "unbound variable". 

More details here: 

Here are the logs: https://paste.yunohost.org/raw/surabonafi

**Comment by Gofannon** [comment]
Same for me and restore failed after upgrade. Wallabag is gone for the user panel

My install is on a subdomain

https://paste.yunohost.org/omimajosoj.sql

**Comment by notarobot63** [comment]
Hello, 
Same error here, but restore is ok. 
Let me know if you need some testing.

**Comment by lapineige** [comment]
#84 should fix it

**Comment by notarobot63** [comment]
Yep, update wen smoothly. Thanks for the quick action !

**Comment by mdic** [comment]
Many thanks for the quick update; had the same wb_conf issue yesterday, and now the update went smoothly!

**Comment by lapineige** [comment]
You can thanks @kay0u for its work and quick action :)
