### ISSUE TITLE
Version relative to upstream repo

### ISSUE THREAD

**Issue by mattbk** [YunoHost-Apps/wallabag2_ynh#85]
I'm looking for this feature, which has been merged into Wallabag master: https://github.com/wallabag/wallabag/pull/4326.

Is it available in the testing branch or any others here?

Any explanation of the version/branch relationship between Wallabag and this repo would be helpful.

**Comment by lapineige** [comment]
We only use releases, listed here: https://github.com/wallabag/wallabag/releases

From what I can see in Wallabag repository, the next one, 2.4.0, is on it's way : https://github.com/wallabag/wallabag/pull/4361 (you can subscribe to be notified if needed)

Once it get merged we usually do a testing branch in a few day (but it's not guaranteed, benevolent work ;).

The only way to get a new version from the master/testing/any other branch from wallabag repo is to fork our repository, and change the URL that find the wallabag source with a new one containing all files in a .tar.gz (and change the checksum too).

**Comment by mattbk** [comment]
Thanks, that led me to the answer I wanted. I was confused about the release schedule, looks like this feature will be out in 2.4.0: https://github.com/wallabag/wallabag/pull/4361/commits/33a1a4a058396723a3a4212a9ff7672d42c916c0#diff-4ac32a78649ca5bdd8e0ba38b7006a1e.

**Comment by lapineige** [comment]
You're welcome :)
