### ISSUE TITLE
Error 500 when accessing wallabag2

### ISSUE THREAD

**Issue by manuelleduc** [YunoHost-Apps/wallabag2_ynh#86]
Hello,

First I must say I'm a huge fan of the work the ynh and wallabag2_ynh team has done over the years.

But since a few days, whenever I try to access my wallabag2 app, I'm welcomed with the error below:

```
Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.
```

I've tried to look at  the nginx logs of the app but it is not telling me much:
```
78.126.73.250 - - [23/Sep/2020:07:45:14 +0000] "GET / HTTP/2.0" 500 781 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0"
```

I'm sorry I can't provide you with more information. I have full access on the server so do not hesitate to ask for more.

PS: The root cause of the issue might be in ynh core since my freshrss app is also not working, and I think it stopped working at the same time.

**Comment by lapineige** [comment]
Did you do any upgrade or configuration change recently ?
Is there any relevant message in wallabag log ?
Is php service running normally ? (what if you restart it ?)

**Comment by manuelleduc** [comment]
I did some unrelated upgrades, here is the list from the tools / log section.

```
yesterday Upgrade the 'nextcloud' app
3 days ago Update user info of 'mleduc'
3 days ago Delete permission 'shellinabox'
3 days ago Remove the 'shellinabox' app
3 days ago Delete permission 'calibreweb'
3 days ago Remove the 'calibreweb' app
3 days ago Update accesses for permission 'redirect__2'
4 days ago Upgrade the 'rainloop' app
4 days ago Upgrade system packages
[...]
```

Probably more interesting, this is the logs from `./var/logs/prod.log`:

```
[2020-09-24 07:40:24] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_controller":"Wallabag\\CoreBundle\\Controller\\EntryController::showUnreadAction","page":1,"_route":"homepage"},"request_uri":"https://wallabag.mleduc.xyz/","method":"GET"} []
[2020-09-24 07:40:24] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Ldap\Exception\LdapException: "The LDAP PHP extension is not enabled." at /var/www/wallabag2/vendor/symfony/symfony/src/Symfony/Component/Ldap/Adapter/ExtLdap/Adapter.php line 29 {"exception":"[object] (Symfony\\Component\\Ldap\\Exception\\LdapException(code: 0): The LDAP PHP extension is not enabled. at /var/www/wallabag2/vendor/symfony/symfony/src/Symfony/Component/Ldap/Adapter/ExtLdap/Adapter.php:29)"} []
```

**Comment by manuelleduc** [comment]
I guess I could instal some `php-ldap` package manually but I don't really want to take the risk to see this interfering with future upgrades.

**Comment by lapineige** [comment]
I don't know if there is any risk if you install that package, maybe someone from @YunoHost-Apps/apps-group could help us here.

I wonder why this error appeared suddenly...

**Comment by ericgaspar** [comment]
you can try to install it and see...
`apt install php7.3-ldap`

**Comment by manuelleduc** [comment]
Thanks all for the advices.

I've fixed the issue by installing `php7.0-ldap` and `php7.0-mysql`.
