### ISSUE TITLE
Upgrade to Wallabag 2.4.2

### ISSUE THREAD

**Issue by lapineige** [YunoHost-Apps/wallabag2_ynh#88]
Wallabag 2.4 has been released : https://github.com/wallabag/wallabag/releases
edit: let's wait for 2.4.1 (see next comment)
edit: 2.4.2 is out https://github.com/wallabag/wallabag/releases/tag/2.4.2

Important notes:
- PHP versions below 7.2 are no longer supported. How do we manage that ? Right now I believe we use php7.3. Are we supposed to handle a php upgrade if needed ? (how ?)
- PHP 7.4 is now supported
- We should run `php bin/console --env=prod wallabag:generate-hashed-urls` after upgrading to 2.4.0 (how can we handle this only for this kind of upgrade ? Should we run it in any case, as it should not create any harm ?)

Also : 
>you can safely remove database_driver_class from the app/config/parameters.yml file

Should we change that ?
And: 

> install imagick PHP extension if you want GIF animation to be kept when saving images locally

**Comment by nicofrand** [comment]
> We should run php bin/console --env=prod wallabag:generate-hashed-urls after upgrading to 2.4.0 (how can we handle this only for this kind of upgrade ? Should we run it in any case, as it should not create any harm ?)

I asked them directly:

![image](https://user-images.githubusercontent.com/3419050/103239320-7211a300-494d-11eb-8035-3f7bd01f7a64.png)

**Comment by JimboJoe** [comment]
I've initiated #90 to begin that work. It's pending 2.4.1 update (which will hopefully fix https://github.com/wallabag/wallabag/issues/4820).
Someone must also handle cleanly the use of PHP 7.3 with latest helpers brought by YunoHost 4.0...

**Comment by lapineige** [comment]
> Someone must also handle cleanly the use of PHP 7.3 with latest helpers brought by YunoHost 4.0...

I have no knowledge about that and no time to learn it until a long while… so that will probably not be me 😅

**Comment by lapineige** [comment]
2.4.2 is out https://github.com/wallabag/wallabag/releases/tag/2.4.2

It's mainly a bug fix release. @JimboJoe could you update your PR #90 to that new version ?
