### ISSUE TITLE
bin/console errors

### ISSUE THREAD

**Issue by biosaat** [YunoHost-Apps/wallabag2_ynh#89]
Hi everyone, 

according to https://doc.wallabag.org/en/admin/console_commands.html `bin/console` should return a list of all console commands. 

When executing `./console` in /var/www/wallabag2/bin as root, I just get the following: 

> PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "SensioGeneratorBundle" from namespace "Sensio\Bundle\GeneratorBundle".
> Did you forget a "use" statement for another namespace? in /var/www/wallabag2/app/AppKernel.php:49
> Stack trace:
> #0 /var/www/wallabag2/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(448): AppKernel->registerBundles()
> #1 /var/www/wallabag2/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(114): Symfony\Component\HttpKernel\Kernel->initializeBundles()
> #2 /var/www/wallabag2/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(60): Symfony\Component\HttpKernel\Kernel->boot()
> #3 /var/www/wallabag2/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(122): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #4 /var/www/wallabag2/bin/console(29): Symfony\Component\C in /var/www/wallabag2/app/AppKernel.php on line 49

Any suggestions how to fix this?

**Comment by JimboJoe** [comment]
From [that reference](https://github.com/wallabag/wallabag/issues/2398), I understand you have to use the `-e=prod`parameter.

**Comment by biosaat** [comment]
Thanks, JimboJoe, that works.

**Comment by lapineige** [comment]
That's good to know :)
