### ISSUE TITLE
[SECURITY] Wallabag database password readable by all users

### ISSUE THREAD

**Issue by Jules-Bertholet** [YunoHost-Apps/wallabag2_ynh#94]
This password can be stored in `$final_path/var/cache/prod/appProdProjectContainer.php`, which all users can read.

**Comment by TROMsite** [comment]
hm....is this true? that seems really bad

**Comment by TROMsite** [comment]
I could not find any passwords stored in that file. Are you sure @Jules-Bertholet  ? And is this an upstream issue or this ynh package issue?

**Comment by Jules-Bertholet** [comment]
@lapineige Last I checked, when I `grep`ped for the database password it was in there (not the master SQL password, but the password for the database Wallabag uses). This is a problem with the permissions the installation script sets on the files, nothing to do with upstream

**Comment by lapineige** [comment]
I also discover this warning in the CI : https://ci-apps-dev.yunohost.org/ci/job/1127

> Error: It looks like anybody can read/enter /var/www/wallabag2, which ain't super great from a security point of view ... Config files or other files may contain secrets or information that should in most case not be world-readable. You should remove all 'others' permissions with 'chmod o-rwx', and setup appropriate, exclusive permissions to the appropriate owner/group with chmod/chown.

Sounds like we might need to refactor all permissions… but that's probably a bigger work.
I believe this issue is more "urgent", even if fixing the overall issue might be more efficient, maybe we should fix that first (that should be a quick and non-breaking change) then fix the whole permission stuff…

**Comment by lapineige** [comment]
> Sounds like we might need to refactor all permissions… but that's probably a bigger work.

Let's do that here: https://github.com/YunoHost-Apps/wallabag2_ynh/tree/better-permissions

And first fix that issue. I would like to merge it as soon as possible, maybe in the same testing than #92 and #93.

**Comment by lapineige** [comment]
Fixed by #99, thank you @Jules-Bertholet :)
