### ISSUE TITLE
Improve backup logs

### ISSUE THREAD

**Issue by lapineige** [YunoHost-Apps/wallabag2_ynh#95]
There is a recommendation here : https://ci-apps-dev.yunohost.org/ci/job/783

```- We recommend to *not* use 'ynh_script_progression' in backup scripts because no actual work happens when running the script  : YunoHost only fetches the list of things to backup (apart from the DB dumps which effectively happens during the script...). Consider using a simple message like this instead: 'ynh_print_info "Declaring files to be backed up..."'```

We could improve that logging operation during backup script, based on this recommendation.
(I have no time to work on this, I'm referencing it as it's 1) not pressing at all and 2) a good first contribution if someone want to try :slightly_smiling_face:)

**Comment by alexAubin** [comment]
Fixed by https://github.com/YunoHost-Apps/wallabag2_ynh/pull/118
